import "./assets/anh_linh.jpg";
import "./assets/gap_thu.jpg";
import "./assets/sinh_ton.jpg";
import "./assets/swiper-bg.png";
import "./assets/fold.png";
import "./assets/paperclip.png";
import "./assets/button_left.png";
import "./assets/button_right.png";
import "./assets/ribbon_button_hover_icon.png";
import "./assets/mobile/swiper-bg-mobile.png";
import "./assets/frame2-bg.jpg";
import "./assets/mobile/frame2-bg-mobile.jpg";

import "./assets/mobile/frame2_title_mobile.png";
import "./assets/frame2_title.png";
import "./assets/cta_frame2.png";
import "./assets/ribbon_button1.png";
import "./assets/ribbon_button2.png";
import "./assets/ribbon_button3.png";
import "./assets/ribbon_button4.png";
import "./assets/mobile/ribbon_button1_mobile.png";
import "./assets/mobile/ribbon_button2_mobile.png";
import "./assets/mobile/ribbon_button3_mobile.png";
import "./assets/mobile/ribbon_button4_mobile.png";

import "./assets/mobile/frame2_title_mobile-en.png";
import "./assets/frame2_title-en.png";
import "./assets/cta_frame2-en.png";
import "./assets/ribbon_button1-en.png";
import "./assets/ribbon_button2-en.png";
import "./assets/ribbon_button3-en.png";
import "./assets/ribbon_button4-en.png";
import "./assets/mobile/ribbon_button1_mobile-en.png";
import "./assets/mobile/ribbon_button2_mobile-en.png";
import "./assets/mobile/ribbon_button3_mobile-en.png";
import "./assets/mobile/ribbon_button4_mobile-en.png";

import "./assets/mobile/frame2_title_mobile-id.png";
import "./assets/frame2_title-id.png";
import "./assets/cta_frame2-id.png";
import "./assets/ribbon_button1-id.png";
import "./assets/ribbon_button2-id.png";
import "./assets/ribbon_button3-id.png";
import "./assets/ribbon_button4-id.png";
import "./assets/mobile/ribbon_button1_mobile-id.png";
import "./assets/mobile/ribbon_button2_mobile-id.png";
import "./assets/mobile/ribbon_button3_mobile-id.png";
import "./assets/mobile/ribbon_button4_mobile-id.png";

import "./assets/mobile/frame2_title_mobile-cn.png";
import "./assets/frame2_title-cn.png";
import "./assets/cta_frame2-cn.png";
import "./assets/ribbon_button1-cn.png";
import "./assets/ribbon_button2-cn.png";
import "./assets/ribbon_button3-cn.png";
import "./assets/ribbon_button4-cn.png";
import "./assets/mobile/ribbon_button1_mobile-cn.png";
import "./assets/mobile/ribbon_button2_mobile-cn.png";
import "./assets/mobile/ribbon_button3_mobile-cn.png";
import "./assets/mobile/ribbon_button4_mobile-cn.png";

// import "./assets/mobile/frame2_title_mobile-th.png";
// import "./assets/frame2_title-th.png";
import "./assets/cta_frame2-th.png";
import "./assets/ribbon_button1-th.png";
import "./assets/ribbon_button2-th.png";
import "./assets/ribbon_button3-th.png";
import "./assets/ribbon_button4-th.png";
import "./assets/mobile/ribbon_button1_mobile-th.png";
import "./assets/mobile/ribbon_button2_mobile-th.png";
import "./assets/mobile/ribbon_button3_mobile-th.png";
import "./assets/mobile/ribbon_button4_mobile-th.png";
